[package]
name = "remotia-buffer-utils-macros"
version = "0.1.1"
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true